### ISSUE TITLE
All warnings become Structured warnings after requiring structured_warnings

### ISSUE THREAD

**Issue by abotalov** [schmidt/structured_warnings#9]
`structured_warnings` is intended to be used by gems in order to provide more information about a place where a warning happened.
However, once `structured_warnings` is required by one library, all other warnings (even those that use just `warn`) become `StructuredWarning`s as well.
That may pollute program output if the library provides a path to the warning in the message.
I think StructuredWarnings shouldn't change the output of usual `warn`s after `require 'structured_warnings`'.

**Comment by schmidt** [comment]
In general, I disagree. I think, it's a valuable feature, that all warnings - including those triggered by ruby core code - are extended by the features provided by `structured_warning`. I can add the gem to my project and then selectively silence warnings emitted by other libraries, if desired. If I was following your suggestion, this would not be possible.

If formatting is your main concern, there might be a way to get the desired effect by configuring a custom [Warner](http://www.rubydoc.info/github/schmidt/structured_warnings/StructuredWarnings/Warner):

```ruby
w = CustomWarner.new
StructuredWarnings.warner = w

# or in a dynamic scope
StructuredWarnings.with_warner(w) do
   ...
end
```

You would need to implement this `CustomWarner` yourself, though.

**Comment by joegaudet** [comment]
@schmidt This effect breaks the expected behaviour of ```Logger#warn``` which means I cannot use it to capture to a buffer and save it. 

This is made worst by the fact that I included a library that includes this library, so I did not even intend to use it. I think it's generally bad practice to monkey patch the standard lib for exactly this reason, especially if a client of the library hasn't intentionally activated this feature.
